root = "." # The root directory of the project
tmp_dir = "tmp" # The temporary directory where air will store its temporary files

[build] # The build configuration
  bin = "tmp/main" # The name of the binary file to be generated after building the project
  # cmd = "go build -o {{.Output}} {{.Input}}" # The command to build the project
  # full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  cmd = "go build -o ./tmp/main ." # The command to build the project
  exclude_dir = ["tmp", "client"]  # Specifies the directories to be excluded from monitoring for changes
  include_ext = ["go", "tpl", "tmpl", "html"] # Specifies the file patterns to be included for monitoring.
